# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_0900_ai_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host:     <%= ENV.fetch("DB_HOST", "db") %>
  port:     <%= ENV.fetch("DB_PORT", 3306) %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  # ローカルではSSL不要。本番のみ使うなら production だけに記載する
  # ssl_mode: required

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "app_test") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "genba_task_production") %>
    url: <%= ENV["DATABASE_URL"] %> # あれば優先

  cable:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "genba_task_production") %>
    url: <%= ENV.fetch("DATABASE_URL_CABLE", ENV["DATABASE_URL"]) %>

  queue:
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "genba_task_production") %>
    url: <%= ENV.fetch("DATABASE_URL_QUEUE", ENV["DATABASE_URL"]) %>
