default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>

development:
  <<: *default
  database: genba_task_dev

test:
  <<: *default
  database: genba_task_test

# 本番は DATABASE_URL を優先利用
production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "genba_task_prod") %>
